import {
  escHtml,
  escOptional,
  htmlToPdfBuffer,
  logoBufferToDataUrl,
  pdfDocumentChrome,
} from "@/lib/pdf/chromium-pdf";
import type { DispatchVoucherPdfFields } from "@/lib/pdf/dispatch-voucher-document";

export function buildDispatchVoucherHtml(
  fields: DispatchVoucherPdfFields,
  logoSource: Buffer | string | null
): string {
  const logoDataUrl =
    typeof logoSource === "string"
      ? logoSource
      : logoBufferToDataUrl(logoSource);

  const hw = [fields.processorName, fields.systemRam, fields.systemGpu]
    .filter(Boolean)
    .join(" · ");
  const makeModel = [fields.manufacturer, fields.model]
    .filter(Boolean)
    .join(" · ");
  const sourceLabel =
    fields.dataSource === "zoho_assist" ? "Zoho Assist" : "Manual";

  const bodyHtml = `
    <h1>Dispatch voucher</h1>
    <p class="ref">${escHtml(fields.referenceNumber)}</p>
    <p class="subtitle">
      Hardware dispatched to the field — retain for finance and audit records.
    </p>

    <div class="meta">
      <div>
        <div class="meta-label">Dispatch date</div>
        <div class="meta-value">${escHtml(fields.dispatchedAt)}</div>
      </div>
      <div>
        <div class="meta-label">From stage</div>
        <div class="meta-value">${escHtml(fields.fromStageLabel)}</div>
      </div>
      <div>
        <div class="meta-label">To stage</div>
        <div class="meta-value">Deployed</div>
      </div>
    </div>

    <h2>Asset details</h2>
    <table class="details">
      <tr><th>Asset name</th><td>${escHtml(fields.assetName)}</td></tr>
      <tr><th>Club / site</th><td>${escOptional(fields.clubName)}</td></tr>
      <tr><th>Category</th><td>${escHtml(fields.category)}</td></tr>
      <tr><th>Make / model</th><td>${escHtml(makeModel || "—")}</td></tr>
      <tr><th>Device template</th><td>${escOptional(fields.templateLabel)}</td></tr>
      <tr><th>Serial number</th><td>${escOptional(fields.serialNumber)}</td></tr>
      <tr><th>Location</th><td>${escOptional(fields.deviceLocation)}</td></tr>
      <tr><th>CPU / RAM / GPU</th><td>${escHtml(hw || "—")}</td></tr>
      <tr><th>Source</th><td>${escHtml(sourceLabel)}</td></tr>
    </table>

    <p class="footer">
      Generated by Handicaps Network Africa Inventory · ${escHtml(fields.referenceNumber)}
    </p>
  `;

  return pdfDocumentChrome({
    title: `Dispatch · ${fields.referenceNumber}`,
    bodyHtml,
    logoDataUrl,
  });
}

/** Chromium print PDF for dispatch vouchers. */
export async function renderDispatchVoucherPdf(
  fields: DispatchVoucherPdfFields,
  logoSource: Buffer | string | null
): Promise<Buffer> {
  return htmlToPdfBuffer(buildDispatchVoucherHtml(fields, logoSource));
}
