import {
  escHtml,
  escOptional,
  htmlToPdfBuffer,
  logoBufferToDataUrl,
  pdfDocumentChrome,
} from "@/lib/pdf/chromium-pdf";

export type WriteOffCertificatePdfFields = {
  referenceNumber: string;
  writtenOffAt: string;
  assetName: string;
  clubName: string | null;
  category: string;
  manufacturer: string | null;
  model: string | null;
  serialNumber: string | null;
  reason: string | null;
  assessmentReference: string | null;
  replacementRequested: boolean;
  replacementNotes: string | null;
  fromStatusLabel: string;
};

export function buildWriteOffCertificateHtml(
  fields: WriteOffCertificatePdfFields,
  logoSource: Buffer | string | null
): string {
  const logoDataUrl =
    typeof logoSource === "string"
      ? logoSource
      : logoBufferToDataUrl(logoSource);

  const makeModel = [fields.manufacturer, fields.model]
    .filter(Boolean)
    .join(" · ");

  const bodyHtml = `
    <h1>Write-off certificate</h1>
    <p class="ref">${escHtml(fields.referenceNumber)}</p>
    <p class="subtitle">
      Official record that this unit has been approved for write-off.
      Retain for finance and audit. Assessment intake references are kept for lineage.
    </p>

    <div class="meta">
      <div>
        <div class="meta-label">Written off</div>
        <div class="meta-value">${escHtml(fields.writtenOffAt)}</div>
      </div>
      <div>
        <div class="meta-label">From stage</div>
        <div class="meta-value">${escHtml(fields.fromStatusLabel)}</div>
      </div>
      <div>
        <div class="meta-label">Status</div>
        <div class="meta-value">Write-off approved</div>
      </div>
    </div>

    <h2>Certificate details</h2>
    <table class="details">
      <tr><th>Club name</th><td>${escOptional(fields.clubName)}</td></tr>
      <tr><th>Asset name</th><td>${escHtml(fields.assetName)}</td></tr>
      <tr><th>Asset type</th><td>${escHtml(fields.category)}</td></tr>
      <tr><th>Make / model</th><td>${escHtml(makeModel || "—")}</td></tr>
      <tr><th>Serial number</th><td>${escOptional(fields.serialNumber)}</td></tr>
      <tr><th>Assessment intake</th><td>${escOptional(fields.assessmentReference)}</td></tr>
      <tr><th>Write-off reason</th><td>${escOptional(fields.reason)}</td></tr>
      <tr><th>Replacement requested</th><td>${fields.replacementRequested ? "Yes" : "No"}</td></tr>
      ${
        fields.replacementRequested && fields.replacementNotes
          ? `<tr><th>Replacement notes</th><td>${escHtml(fields.replacementNotes)}</td></tr>`
          : ""
      }
    </table>

    <p class="footer">
      Generated by Handicaps Network Africa Inventory · ${escHtml(fields.referenceNumber)} · Write-off approved
    </p>
  `;

  return pdfDocumentChrome({
    title: `Write-off · ${fields.referenceNumber}`,
    bodyHtml,
    logoDataUrl,
    watermarkText: "WRITE-OFF APPROVED",
  });
}

export async function renderWriteOffCertificatePdf(
  fields: WriteOffCertificatePdfFields,
  logoSource: Buffer | string | null
): Promise<Buffer> {
  const html = buildWriteOffCertificateHtml(fields, logoSource);
  return htmlToPdfBuffer(html);
}
